### ISSUE TITLE
新字幕需要做下断句

### ISSUE THREAD

**Issue by 95uxin** [95uxin/co-subtitles#5]
@Noire961030

**Comment by Noire961030** [comment]
你改？还是我改？

2017年4月4日 下午3:27，"Yuxin Wu" <notifications@github.com>写道：

**Comment by 95uxin** [comment]
你先试试

**Comment by Noire961030** [comment]
嗯，OK


2017年4月4日 下午4:50，"Yuxin Wu" <notifications@github.com>写道：

> 你先试试
>

**Comment by Noire961030** [comment]
是调文本，还是调时间？你上次怎么调的？我参考下，看看怎么弄好一点。

2017年4月4日 下午4:56，"张思齐" <zhangsiqi961030@gmail.com>写道：

> 嗯，OK
>
>
> 2017年4月4日 下午4:50，"Yuxin Wu" <notifications@github.com>写道：
>
>> 你先试试
>>

**Comment by 95uxin** [comment]
都调

**Comment by 95uxin** [comment]
@Noire961030 有些地方会有一行就几个字，有些几个字占很长时间

**Comment by Noire961030** [comment]
了解

2017年4月4日 下午6:03，"Yuxin Wu" <notifications@github.com>写道：

**Comment by Noire961030** [comment]
时时

2017年4月5日 下午6:41，写道：

特殊

**Comment by Noire961030** [comment]
特殊
